name: studify

networks:
  studify-net:
    driver: bridge
    name: studify-net

services:
  user-db:
    image: mariadb:11.4
    container_name: user-db
    environment:
      MARIADB_DATABASE: studify-user
      MARIADB_USER: ${USER:-root}
      MARIADB_PASSWORD: ${PASSWD:-root}
      MARIADB_ROOT_PASSWORD: ${PASSWD:-root}
    ports: ["3307:3306"]   # 외부 점검용, 운영땐 제거 가능
    volumes:
      - userdb-data:/var/lib/mysql
    networks: [ studify-net ]
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p${PASSWD:-root} --host=127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  post-db:
    image: mariadb:11.4
    container_name: post-db
    environment:
      MARIADB_DATABASE: studify-post
      MARIADB_USER: ${USER:-root}
      MARIADB_PASSWORD: ${PASSWD:-root}
      MARIADB_ROOT_PASSWORD: ${PASSWD:-root}
    ports: ["3308:3306"]   # 외부 점검용, 운영땐 제거 가능
    volumes:
      - postdb-data:/var/lib/mysql
    networks: [ studify-net ]
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p${PASSWD:-root} --host=127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  userdb-data:
  postdb-data:
