name: studify

networks:
  studify-net:
    external: true

services:
  nginx-proxy:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d
    networks: [ studify-net ]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/nginx/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
