name: Build & Push Images

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "studify-msa/**"
      - ".github/workflows/build-push.yml"

jobs:
  matrix-builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          set -e
          git fetch --depth=2 origin $GITHUB_REF || true
          changed() { git diff --name-only HEAD~1 HEAD -- "$1" >/dev/null 2>&1; }
          SERVICES=()
          changed studify-msa/eureka-server && SERVICES+=("eureka-server")
          changed studify-msa/api-gateway && SERVICES+=("api-gateway")
          changed studify-msa/user-service && SERVICES+=("user-service")
          changed studify-msa/post-service && SERVICES+=("post-service")
          changed studify-msa/notification-service && SERVICES+=("notification-service")
          if [ ${#SERVICES[@]} -eq 0 ]; then echo 'matrix={"service":[]}' >> $GITHUB_OUTPUT; exit 0; fi
          printf 'matrix={"service":[' >> $GITHUB_OUTPUT
          printf '"%s",' "${SERVICES[@]}" | sed 's/,$//' >> $GITHUB_OUTPUT
          printf ']}\n' >> $GITHUB_OUTPUT

  build-push:
    needs: matrix-builder
    if: ${{ needs.matrix-builder.outputs.matrix != '{"service":[]}' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.matrix-builder.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}

      - id: meta
        run: |
          echo "image=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.service }}" >> $GITHUB_OUTPUT
          echo "tag1=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "tag2=latest" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: studify-msa/${{ matrix.service }}
          file: studify-msa/${{ matrix.service }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag1 }}
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
