name: Deploy to EC2
concurrency:
  group: ec2-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image TAG (default: latest)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Read previous TAG on EC2
        id: prev
        run: |
          echo "prev=$(ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "grep -E '^TAG=' /home/ubuntu/studify-be/.env | cut -d= -f2 || echo latest")" >> $GITHUB_OUTPUT

      - name: Rsync app bundle
        run: |
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            app/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/studify-be/

      - name: Inject .env on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "cd /home/ubuntu/studify-be && \
            touch .env && \
            sed -i '/^DRIVER=/d;/^URL=/d;/^USER=/d;/^PASSWD=/d;/^EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=/d;/^TAG=/d;/^DOCKERHUB_USERNAME=/d' .env || true; \
            [ -n '${{ secrets.DRIVER }}' ] && echo 'DRIVER=${{ secrets.DRIVER }}' >> .env || true; \
            echo 'URL=${{ secrets.URL }}' >> .env; \
            echo 'USER=${{ secrets.USER }}' >> .env; \
            echo 'PASSWD=${{ secrets.PASSWD }}' >> .env; \
            echo 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${{ secrets.EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE }}' >> .env; \
            [ -n '${{ secrets.DOCKERHUB_USERNAME }}' ] && echo 'DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}' >> .env || true; \
            echo 'TAG=${{ github.event.inputs.tag || secrets.TAG_DEFAULT || 'latest' }}' >> .env; \
            chmod +x deploy/*.sh"

      - name: Compose up (remote)
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "bash /home/ubuntu/studify-be/deploy/start.sh"

      - name: Smoketest (gateway)
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Rolling back to TAG=${{ steps.prev.outputs.prev }}"
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "cd /home/ubuntu/studify-be && \
            sed -i 's/^TAG=.*/TAG=${{ steps.prev.outputs.prev }}/' .env && \
            bash /home/ubuntu/studify-be/deploy/start.sh"

